# Generated by Django 5.0.3 on 2024-08-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0002_author_blog_entry_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
